### ISSUE TITLE
feedback gebruikersdag 2023

### ISSUE THREAD

**Issue by MatthiasHauthDeltares** [Deltares-research/VrtoolDashboard#155]
## 11 December 2023

- [x] Make export result as shapefiles: [85](https://github.com/Deltares-research/VrtoolDashboard/issues/85)
- [x] Investments years: see issue [149](https://github.com/Deltares-research/VrtoolDashboard/issues/149)
- [x] Soil reinforcement dberm=dcrest=0 should not be displayed [153](https://github.com/Deltares-research/VrtoolDashboard/issues/153)
- [ ] Revetment: transition level, is it Grass or Stone?
- [x] Show Path of all steps from greedy algorithm [151](https://github.com/Deltares-research/VrtoolDashboard/issues/151)
- [x] Collapse-able menus are not self explanatory (add a link to documentation)

## 24 October 2023

- [x] Add a graph beta Vs euros displaying all measures of a given dijkvak (if too slow, show the best 10 measures) (sill relevant)
- [ ] Show between all mechanism, which one has the highest "improvement ratio": beta_before_reinf /beta_after_reinf (nice to have)
- [x] Show graph beta versus time: [60](https://github.com/Deltares-research/VrtoolDashboard/issues/60)
